#!/bin/bash -l
GIT_REPO=$HOME/repos/sammorr.is.git
TMP_GIT_CLONE=$HOME/tmp/git/sammorr.is
PUBLIC_WWW=/var/www/sammorr.is/public_html
SUBDOMAIN_FOLDER=/var/www/sammorr.is/subdomains/*

git clone $GIT_REPO $TMP_GIT_CLONE
jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
cp -R $SUBDOMAIN_FOLDER $PUBLIC_WWW
rm -Rf $TMP_GIT_CLONE
exit
